apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: {{ .Values.kraftController.name }}
  annotations:
    platform.confluent.io/broker-id-offset: {{ .Values.controllerIdOffset | quote }}
spec:
  replicas: {{ .Values.kraftController.replicas }}
  {{- if .Values.cluster.clusterID }}
  clusterID: {{ .Values.cluster.clusterID | quote }}
  {{- end }}
  {{- if .Values.authorization.enabled }}
  authorization:
    type: simple
    superUsers:
      {{- range .Values.authorization.superUsers }}
      - {{ . }}
      {{- end }}
  {{- end }}
  image:
    application: {{ .Values.image.controllerApplication }}
    init: {{ .Values.image.controllerInit }}
  dataVolumeCapacity: {{ .Values.kraftController.storage.size }}
  {{- if .Values.kraftController.storage.class }}
  storageClass:
    name: {{ .Values.kraftController.storage.class }}
  {{- end }}
  # TLS configuration for the KRaft controller
  {{- if .Values.tls.enabled }}
  tls:
    secretRef: kraftcontroller-tls
  {{- end }}
  podTemplate:
    resources:
      requests:
        cpu: {{ .Values.kraftController.resources.requests.cpu | quote }}
        memory: {{ .Values.kraftController.resources.requests.memory | quote }}
      limits:
        cpu: {{ .Values.kraftController.resources.limits.cpu | quote }}
        memory: {{ .Values.kraftController.resources.limits.memory | quote }}
    affinity:
      podAntiAffinity:
        {{- if not .Values.nodeSelector.enabled }}
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: kraftcontroller
              topologyKey: kubernetes.io/hostname
        {{- else }}
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: kraftcontroller
            topologyKey: kubernetes.io/hostname
        {{- end }}
    {{- if and (not .Values.standalone) .Values.nodeSelector.enabled }}
    nodeSelector:
      topology.kubernetes.io/region: {{ .Values.region.name }}
    {{- end }}
  {{- if or .Values.authorization.enabled .Values.staticQuorumVoters .Values.tls.mtls.enabled }}
  configOverrides:
    server:
      {{- if .Values.tls.mtls.enabled }}
      - listener.name.controller.ssl.client.auth=required
      {{- end }}
      {{- if .Values.staticQuorumVoters }}
      - controller.quorum.voters={{ range $i, $v := .Values.staticQuorumVoters }}{{ if $i }},{{ end }}{{ $v.nodeId }}@{{ $v.brokerEndpoint }}{{ end }}
      {{- end }}
      {{- if .Values.authorization.enabled }}
      - authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - confluent.authorizer.access.rule.providers=KRAFT_ACL
      {{- range .Values.authorization.superUsers }}
      - super.users={{ . }}
      {{- end }}
      {{- end }}
  {{- end }}
  listeners:
    controller:
      tls:
        enabled: {{ .Values.tls.enabled }}
        {{- if .Values.tls.enabled }}
        secretRef: kraftcontroller-tls
        {{- end }}